name: "Refresh Python Dependency"
description: "Refresh your dependency files in a Python repo"
inputs:
  path:
    description: "dependency file"
    required: false
    default: "requirements.txt"
  extra_path:
    description: "another dependency file"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Run pip-check-updates
      shell: bash
      run: |
        pip install pip-check-updates
        pcu ${{ inputs.path }} -u
        [[ "${{ inputs.extra_path }}" = true ]] && pcu ${{ inputs.extra_path }} -u || true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: refresh deps
        committer: GitHub <noreply@github.com>
        author: pcu-bot <pcu-bot@users.noreply.github.com>
        signoff: false
        branch: pcu-pr
        delete-branch: true
        title: "[pcu] Refresh Deps"
branding:
  icon: "box"
  color: "purple"
