name: "Refresh Python Dependency"
description: "Refresh your dependency files in a Python repo"
inputs:
  path:
    description: "dependency file"
    required: false
    default: "requirements.txt"
  branch:
    description: "branch name"
    required: false
    default: "pcu-pr"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Run pip-check-updates
      shell: bash
      run: |
        pip install pip-check-updates
        pcu ${{ inputs.path }} -u --loggable
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: refresh deps
        committer: GitHub <noreply@github.com>
        author: pcu-bot <pcu-bot@users.noreply.github.com>
        signoff: false
        branch: ${{ inputs.branch }}
        delete-branch: true
        title: "[pcu] Refresh Deps"
branding:
  icon: "box"
  color: "purple"
